### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by rfischmann** [The-Network-Crew/TNC-Toolbox-for-WordPress#19]
Hi,

I've installed, activated and configured the plugin with cPanel's API details, but it doesn't seem to be working for me; NGINX's cache doesn't update when we publish or edit posts in WordPress.

How can we debug this together, please?

Thank you!

**Comment by lsthompson** [comment]
Hi there, we have a decent number of sites running it successfully.

Please confirm the version you're running, and show the result of a manual cache purge?

Also, you're sure that the correct cPanel is entered into the config? You can successfully wrongly configure it.
